### ISSUE TITLE
Не могу запустить vkcoin.py хотя vk_api установлен

### ISSUE THREAD

**Issue by fwflunky** [theunravelghoul/VKCoinPy#1]
![Screenshot_20190406_222838_com sonelli juicessh](https://user-images.githubusercontent.com/38854160/55671583-b4fb2f80-58bb-11e9-9b9e-41d39bec5eb2.jpg)

**Comment by theunravelghoul** [comment]
Видимо, зависимости были устанвовлены для встроенного в систему Python 2.7. 
Выкатил небольшой апдейт, можно попробовать сделать все через sh скрипты:

```bash
chmod +x install.sh
./install.sh
chmod +x start.sh
./start.sh
```

**Comment by fwflunky** [comment]
Все, спасибо! Желаю развития этого скрипта и чтобы он не прекращал работать)!
