### ISSUE TITLE
Умная автозакупка не работает

### ISSUE THREAD

**Issue by hkJgu8rG0qaWcvaPu3vhlycaKc2Tfb8u** [theunravelghoul/VKCoinPy#11]
Вроде как что-то там про умную покупку написано в коде, но проверив я был в недоразумении, ваша умная покупка потратила 180 000,000 на 9 датацентров и итоговая скорость вышла в жалкие 9/сек, умная покупка которую я сделал на костылях (из VCoin) тратит так же 180 000,000, но итоговая скорость-то выходит под 19. Сделайте, пожалуйста, нормальную закупку, или придётся опять мне.

**Comment by DeNcHiK3713** [comment]
Есть небольшой баг(по-крайней мере у меня). Нужно купить хотя бы по 1 каждому предмету, чтобы эти предметы покупались автоматически. Видимо, у вас были куплены только датацентры, поэтому только они и покупались

**Comment by DeNcHiK3713** [comment]
Еще небольшой баг, количество видеокарт на одном аккаунте у меня отображается 0
Отмеченое точкой в начале я покупал сам, все остальное(не включая закупку по одному предмету) покупалось автоматически
![cmd_2Kp6DYnPAY](https://user-images.githubusercontent.com/35270280/55872506-df880980-5b95-11e9-9a5e-5fb298e49ad1.png)

**Comment by hkJgu8rG0qaWcvaPu3vhlycaKc2Tfb8u** [comment]
Пришлось самому сделать

**Comment by theunravelghoul** [comment]
Поправил, проверяйте.

**Comment by DeNcHiK3713** [comment]
У меня одного вечные реконекты?

**Comment by theunravelghoul** [comment]
Нет, только что что-то обновилось в VK Coin.

**Comment by DeNcHiK3713** [comment]
Может нужна помощь? Могу через nox + Charles посмотреть пакеты.
