### ISSUE TITLE
Клиентская библиотека для VK-Coin

### ISSUE THREAD

**Issue by breitburg** [theunravelghoul/VKCoinPy#14]
Предлагаю написать клиентскую библиотеку для VK-Coin. Появилось много людей желающих иметь API к своему кошельку вк-коинов для личных нужд. Например, получать уведомления о поступлениях новых коинов, отправлять коины, получать информацию о балансе и другие функции. Тем-более это будет очень упростило бы жизнь для создателей ботов в ВК (боты в пабликах) взаимодействующих с VK-Coin.

К сожалению у меня не достаточно знаний об устройстве VK-Coin для написания подобной библиотеки. Но если вас это заинтересует, я помогу с чем смогу.

**Comment by Zandari** [comment]
Жду, очень сильно поможет

**Comment by Zandari** [comment]
Если кто-нибудь знает как перевести коины пользователю, напишите, сильно мне поможете

**Comment by breitburg** [comment]
Получил ответ от поддержки ВК...

![image](https://user-images.githubusercontent.com/25728414/56037705-9e7c2a80-5d38-11e9-9731-a0233fd2edee.png)

**Comment by ketsu8** [comment]
```
```

**Comment by breitburg** [comment]
https://github.com/crinny/vkcoin
