### ISSUE TITLE
Не работает, ошибка в синтаксисе

### ISSUE THREAD

**Issue by fwflunky** [theunravelghoul/VKCoinPy#2]
![Screenshot_20190407_021355_com sonelli juicessh](https://user-images.githubusercontent.com/38854160/55674289-0b2c9a80-58dd-11e9-8e6f-2341b9c37be8.jpg)

**Comment by theunravelghoul** [comment]
Версия Python не та, скорее всего, что-то до 3.5.

**Comment by fwflunky** [comment]
Так версия что была 3 часа назад работала

**Comment by fwflunky** [comment]
У меня python3.7

**Comment by theunravelghoul** [comment]
Попробуй обнови сейчас и попробуй.

**Comment by fwflunky** [comment]
Нет, все так же

**Comment by fwflunky** [comment]
Ой я тупенький) Забыл в start.sh поменять python3 на python3.7

**Comment by theunravelghoul** [comment]
Завелось?

**Comment by fwflunky** [comment]
Да

**Comment by fwflunky** [comment]
А нет вот ещё проблема
![Screenshot_20190407_031322_com sonelli juicessh](https://user-images.githubusercontent.com/38854160/55674758-27cbd100-58e3-11e9-8d00-e4007c00946d.jpg)

**Comment by theunravelghoul** [comment]
Попробуй еще раз обновить, если не поможет - нужен будет расширенный токен.
