### ISSUE TITLE
Не помогло( Опять неработает.

### ISSUE THREAD

**Issue by fwflunky** [theunravelghoul/VKCoinPy#3]
Как получить расширенный токен?

**Comment by fwflunky** [comment]
![Screenshot_20190407_124727_com guoshi httpcanary](https://user-images.githubusercontent.com/38854160/55679305-56719800-5933-11e9-94f3-5a00b83d063d.jpg)

**Comment by theunravelghoul** [comment]
Проблемы с токеном.
