### ISSUE TITLE
У вас тоже такая проблемма? Я поставил свои логин и пароль, но пишет только реконекты :(

### ISSUE THREAD

**Issue by ghost** [theunravelghoul/VKCoinPy#4]
```
Bot ID345211991 | Connection closed, reconnecting
```

**Comment by theunravelghoul** [comment]
Проверь, не запущен ли у тебя бот два раза одновременно в нескольких окнах. 
Постоянные реконнекты могут падать, если ты еще откуда-то подключаешься.
