### ISSUE TITLE
Идея автозакупа

### ISSUE THREAD

**Issue by DeNcHiK3713** [theunravelghoul/VKCoinPy#5]
Все работает! Вот идея для оптимального автозакупа: если куроср приносит в ~3 раза меньше чем видеокарта, то цена за покупку видеокарты может быть в ~3 раза больше, чем курсора

**Comment by theunravelghoul** [comment]
Умная автозакупка будет, да.

**Comment by DeNcHiK3713** [comment]
небольшой недочет: количество вешей в консоли отоброжается на 1 меньше

**Comment by theunravelghoul** [comment]
@DeNcHiK3713 проверю, спасибо.

**Comment by DeNcHiK3713** [comment]
Вам спасибо. Появилось еще 1 идея, которую, скорее всего, будет трудно реализовать: сделать умное распределение коинов между всеми ботами, чтобы они равномерно прокачивались

**Comment by DeNcHiK3713** [comment]
И как поменять язык?

**Comment by theunravelghoul** [comment]
Ставится системный язык.

**Comment by DeNcHiK3713** [comment]
Язык системы Русский (Беларусь), ставится английский. Но для меня это не критично

**Comment by theunravelghoul** [comment]
Если Windows - она может не подхватывать файлы перевода.
Решение - запускать из командной строки, а не через батник.

**Comment by DeNcHiK3713** [comment]
Спасибо большое.
