### ISSUE TITLE
Все крашится при первой же ошибке

### ISSUE THREAD

**Issue by azat-ismagilov** [theunravelghoul/VKCoinPy#7]
Если один из аккаунтов по тем или иным причинам не добавляются, все следующие аккаунты - тоже перестают добавляться. В итоге если у тебя есть 20 аккаунтов, и одна ошибка на 5 аккаунте, он добавит только 4.

**Comment by awbait** [comment]
У меня вроде остальные добавляются, но стоит добавить информацию, какой аккаунт не смог загрузиться.

**Comment by theunravelghoul** [comment]
Обновил, должно исправиться.

**Comment by theunravelghoul** [comment]
Закрываю, вроде исправлено.
